name: "EXAMPLE-Mqtt"
description: "Home Assistant MQTT .NET EXAMPLE Add-on"
version: "1.0.3"
slug: "example_mqtt"
startup: application
boot: manual
init: false
arch:
  - aarch64
  - amd64
  - armv7
services:
  - 'mqtt:need'
options:
  Interval: '00:01:10'
  Mqtt: 
    UseAutoConfig: true
    Host: ''
    Port: 1883
    Id: ''
    Pw: ''
    Tls: false
  LogLevel: 'Trace'
schema:
  Interval: str
  Mqtt: 
    UseAutoConfig: bool
    Host: str?
    Port: "int(0,65535)?"
    Id: str?
    Pw: password?
    Tls: bool?
  LogLevel: list(Trace|Debug|Information|Warning|Error|Critical|None)